[package]
name = "pngme"
version = "0.1.0"
edition = "2021"
description = "A command line tool that embedding and displaying secret messages in PNG files."

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
crc = "3.2.1"
